# Generated by Django 3.0.3 on 2020-05-15 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_additionalimage_bb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='contacts',
        ),
    ]
